for x in range(1,11):
    print(f'TEAM{x:02}_AD')
    print(f'TEAM{x:02}_Client_1')
    print(f'TEAM{x:02}_Client_2')
    print(f'TEAM{x:02}_Client_3')
    print(f'TEAM{x:02}_Client_4')
    print(f'TEAM{x}-DB')
    print(f'TEAM{x}-WEB')
    print(f'TEAM{x}-FTP')
    print(f'TEAM{x:02}_Router')